### ISSUE TITLE
Handle @deprecated

### ISSUE THREAD

**Issue by AgnesToulet** [grafana/terraform-provider-schemas#14]
Some fields are marked as deprecated in the schemas (i.e. Loki data query [`range`](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/dataquery.cue#L44) field). They should have a [deprecation message](https://developer.hashicorp.com/terraform/plugin/framework/deprecations) in the provider.

**Comment by undef1nd** [comment]
@AgnesToulet this can be closed as done, I believe.
